<?php
/**
 * @author epointal
 * lf-hiker 
 * Template for map
 */
if ( ! defined( 'ABSPATH' ) ) exit;

?>
<!-- -div of map -->
<div  id="lfh-<?=$map_count?>-skin" class="lfh-container <?=$options['class']?>" style="position:relative;width:<?=$options['width']?>%;">
<div id="lfh-<?=$map_count?>-fadable" class="lfh-fadable <?php echo ($is_connected>0? ' fakefull':'');?>">
    <div id="lfh-<?=$map_count?>" class="lfh-map" style="height:<?=($options['height'])?>px;width:100%;">
    </div>
    <div id="lfh-<?=$map_count?>-data" class="lfh-data simple-border" >
        <div id="lfh-list-<?=$map_count?>" class="lfh-info-<?=$map_count?> lfh-element lfh-list lfh-hidden step0"  >
            <div>
                <div class="lfh-head">
                    <h3 >
                        <span class="lfh-trackname"><?=ucfirst(__('list', 'lfh'))?>&nbsp;</span>
                        <span  class="lfh-close lfhicon lfhicon-close" >&nbsp;</span>
                    </h3>
                </div>
                
                <!-- misc info -->
                <div class="lfh-element-content">
                <div class="lfh-section">
                        
                  <div class="lfh-content lfh-description" >
                 
                  </div>
                </div>
                 
                </div>
            </div>
        </div>
        <div id="lfh-<?=$map_count?>-nav" class="lfh-nav">
            <div class="lfh-title" >
                <span class="lfh-trackname"><?=ucfirst(__('information', 'lfh'))?></span>
                <span class="lfh-close lfhicon lfhicon-close"></span>
            </div>
            <div  class="lfh-back lfhicon lfhicon-chevron-circle-left" style=""></div>
            <div  class="lfh-next lfhicon lfhicon-chevron-circle-right"></div>
        </div>
         
        <div class="lfh-data-content" >
            <div >
                <?=__('Click following button or element on the map to see information about it.', 'lfh')?>
            </div>
            <div class="lfh-contributor">
                <a href="https://wordpress.org/plugins/lf-hiker/" title="Plugin Lf Hiker">Lf Hiker</a>
                | <a href="http://elisabeth.pointal.org" title="Elisabeth Pointal">E.Pointal</a>
                contributor
            </div>
        </div>
    </div>
</div>
</div>
<!-- div of list objets -->



