<?php
/**
 * Template to edit marker parameters in helper or lfh-map type editr 
 * used in views/back/editor/helper.phtml and in Tools/Editor/Map.php
 */
if ( ! defined( 'ABSPATH' ) ) exit;

$class = 'lfh-container';
if (isset($is_map_type)) {
    $class = ' lfh-map-editor';
}
?>

<div class="<?=$class?>" >

<!-- control for marker on map -->
<div id="lfh-control" class="leaflet-bar leaflet-control">
<?php if (isset($is_map_type)):?>
  <a  id="lfh-edit-map" class="leaflet-buttons-control-button marker-control" title="<?=_e('Edit map', 'lfh')?>">
        <div class="lfhicon lfhicon-map"></div>
    </a>
    <a id="lfh-add-element" class="leaflet-buttons-control-button marker-control" title="<?=_e('Add marker or gpx', 'lfh')?>">
        <div class="lfhicon-plus"></div>
    </a>
    <div class="lfh-add-list" >
      <a id="lfh-add-marker" class="leaflet-buttons-control-button marker-control item-list" title="<?=_e('Add marker', 'lfh')?>">
         <div class="lfhicon lfhicon-map-marker"></div>
      </a>
      <a id="lfh-add-gpx" class="leaflet-buttons-control-button marker-control item-list" title="<?=_e('Add gpx', 'lfh')?>">
         <div class="lfhicon lfhicon-road"></div>
      </a>
     </div> 
    <a  id="lfh-delete-marker" class="leaflet-buttons-control-button marker-control" title="<?=_e('Delete marker', 'lfh')?>">
        <div class="lfhicon lfhicon-trash"></div>
    </a>
<?php else:?> 
 <a  id="lfh-edit-map" class="leaflet-buttons-control-button marker-control" title="<?=_e('Edit map', 'lfh')?>">
        <div class="lfhicon lfhicon-map"></div>
    </a>
    <a id="lfh-add-marker" class="leaflet-buttons-control-button marker-control " title="<?=_e('Add marker', 'lfh')?>">
        <div class="lfhicon lfhicon-map-marker"></div>
    </a>
    <a id="lfh-edit-marker" class="leaflet-buttons-control-button marker-control" title="<?=_e('Edit marker', 'lfh')?>">
        <div class="lfhicon lfhicon-edit"></div>
    </a> 
    <a  id="lfh-delete-marker" class="leaflet-buttons-control-button marker-control" title="<?=_e('Delete marker', 'lfh')?>">
        <div class="lfhicon lfhicon-trash"></div>
    </a>  
<?php endif;?>   
</div>
<?php if (!isset($is_map_type)):?>
<!-- banner buttons bottom right -->
     <div id="banner" class="lfh-helper">
         <input name="lfh-cancel" type="button" value="<?=_e('Cancel')?>" />
         <input name="lfh-insert" type="button" value="<?=_e('Insert shortcodes', 'lfh')?>" />
     </div>
<?php endif;?>     
<!-- window for edit map -->
<?php  include 'map-form.phtml';?>

<?php  include 'marker-form.phtml'; ?>
    

    <!-- the map -->
    <div id="map" style="height:100vh;width:100%;"></div>
    <?php if (isset($is_map_type)):?>
    <div><?php var_dump($post->post_content);?></div>
<textarea class="wp-editor-area" style="height: 300px; margin-top: 37px; display: block;" autocomplete="off" cols="40" name="content" id="content" aria-hidden="true">
<?php echo $post->post_content;?>
</textarea>
<?php endif;?>
    </div>