<?php
/**
 * @author epointal
 * HELPER page, for iframe, free from Wordpress admin load by tinyMCE
 * This page is called in post editing page for create the map and markers shortcodes, 
 */
if ( ! defined( 'ABSPATH' ) ) exit;

?>
<!DOCTYPE html>
<html>
    <head>
    <?php wp_print_styles();?>
    </head>

    <body>
    <div id="fade" class="hidden lfh-helper">
  <div class="modal lfh-modal">
    <h3><?=__('Insert shortcodes', 'lfh')?></h3>
    <div class="content">
        <div>
            <label for="lfh-insert-map"><?=__('Insert map shortcode' , 'lfh')?></label>
            <input type="checkbox" name="lfh-insert-map" />
        </div>
         <div>
            <label for="lfh-insert-markers"><?=__('Insert markers shortcodes' , 'lfh')?></label>
            <input type="checkbox" name="lfh-insert-markers" checked />
        </div>
        <div style="text-align:right;margin:10px 5px 5px 0;">
            <input type="button" name="lfh-modal-cancel" value="<?=__('Cancel')?>" />
            <input type="button" name="lfh-modal-insert" value="<?=__('Insert shortcodes', 'lfh')?>" />
        </div>
    </div>
    </div>
    </div>
     <?php include_once 'helper-body.phtml';?>

<!-- all scripts -->
<?php wp_footer();?>
    </body>
</html>