<?php
/**
 * Template to edit map in helper and lfh-map post type editor
 * data come from array Lfh_Model_Map::map_parameters()
 * used in views/back/editor/helper-body.phtml
 */
if ( ! defined( 'ABSPATH' ) ) exit;
?>
<div id="window-edit-map"  class="lfh-form-edit lfh-helper" style="display:none;">
   <div class="header" >
        <h3><?=_e('Edit map', 'lfh')?></h3>
        <div class="lfhicon lfhicon-close"></div>
    </div>
    <form>
    <table>
    <?php $i=0;?>
     <?php foreach( $options_map as $key => $param):?>
     <?php $i++;
           $default = isset($param['default'])? $param['default']: $param['options']['default'];
           $before = isset($param['before'])? $param['before']:'';
           $after = isset($param['after'])? $param['after']:'';
           $class = isset($param['class'])? ' class="' . $param['class'] .'"' :'';
           $global = isset($param['global'])? 'lfh-form-global-'.$key: null;
           $disabled = '';
           if (!is_null($global)) {
               $disabled = "disabled";
           }
           $id = "lfh-form-map-" . $key;
           $label = $param['label'];
     ?>
    
     <?php switch($param['type']):
        case 'checkbox':?>
            <tr <?=$class?>>
                <td>
                <label for="<?=$id?>"><?=$param['label']?></label>
                </td>
                <td>
                <?php if(!is_null($global)):?>
                    <input type="checkbox" class="<?=$global?>" checked title="<?=__('Take the overall value', 'lfh')?>"/>
                <?php endif;?>
                <td>
                <?=$before?>
                <?php if($default):?>
                <input type="checkbox" name="<?=$id?>" tabindex="<?=$i?>" <?=$disabled?> checked />
                <?php else :?>
                 <input type="checkbox" name="<?=$id?>" tabindex="<?=$i?>" <?=$disabled?> />
                <?php endif;?>
                <?=$after?>
                </td>
            </tr>
        <?php break;?>
        
        <?php case 'number':?>
            <?php 
            $min = isset($param['options']['min_range'])? 'min="'. $param['options']['min_range'] .'"' : '';
            $max = isset($param['options']['max_range'])? 'max="'. $param['options']['max_range'] .'"' : '';
            $step = isset($param['options']['step_range'])? 'step="'. $param['options']['step_range'] .'"' : '';?>
            <tr <?=$class?>>
                 <td>
                 <label for="<?=$id?>"><?=$param['label']?></label>
                 </td>
                 <td>
                 </td>
                 <td>
                 <?=$before?>
                <input type="number" name="<?=$id?>" <?=$min?> <?=$max?> <?=$step?> tabindex="<?=$i?>" value="<?=$default?>"/>
                <?=$after?>
                </td>
             </tr>
        <?php break; ?>
        
        <?php case 'select':?>
            <tr <?=$class?>>
                <td>
                <label for="<?=$id?>"><?=$param['label']?></label>
                </td>
                <td>
                <?php if(!is_null($global)):?>
                   <input type="checkbox" class="<?=$global?>" checked title="<?=__('Take the overall value', 'lfh')?>"/>
                <?php endif;?>
                </td>
                <td>
                <?=$before?>
                <select name="<?=$id?>"  tabindex="<?=$i?>" <?=$disabled?>>
                <?php $options = $param['list']?>
                <?php  for($j=0; $j<count($options);$j++): ?>
                <?php 
                  $op_key = isset($options[$j]['key'])? $options[$j]['key']:$options[$j];
                  $op_value = isset($options[$j]['value'])? $options[$j]['value']:$options[$j];
                 ?>
                <?php if($default == $options[$j]):?>
                    <option value="<?=$op_key?>" selected><?=$op_value?></option>
                <?php else : ?>
                    <option value="<?=$op_key?>" ><?=$op_value?></option>
                <?php endif; ?>
                <?php endfor;?>
                </select>
                <?=$after?>
                </td>
            </tr>
        <?php break;?>
        
        <?php case 'datalist':?>
            <tr <?=$class?>>
                <td>
                <label for="<?=$id?>"><?=$param['label']?></label>
                </td>
                <td>
                </td>
                <td>
                <?=$before?>
                 <input name="<?=$id?>"  type="datalist" list="map-<?=$key?>-list" tabindex="<?=$i?>" >
                <?php $options = $param['list']?>
                <datalist id="map-<?=$key?>-list">
                <?php  for($j=0; $j<count($options);$j++): ?>
                    <option value="<?=$options[$j]?>" />
                <?php endfor;?>
                </datalist>
                <?=$after?>
                </td>
            </tr>
        <?php break;?>
        <?php case 'group':?>
          <tr <?=$class?>>
             <td>
                <label for="<?=$id?>"><?=$param['label']?></label>
             </td>
             <td></td>
             <td>
                <?=$before?>
                <?php if($default):?>
                <input type="checkbox" name="<?=$id?>" tabindex="<?=$i?>"  checked />
                <?php else :?>
                 <input type="checkbox" name="<?=$id?>" tabindex="<?=$i?>" />
                <?php endif;?>
                <?=$after?>
             </td>
          </tr>
        <?php break;?>
        <?php case "hidden": ?>
        <?php $i--;?>
        <tr><td>
        <input type="hidden" name="<?=$id?>" value="<?=$default?>"/>
        </td>
        </tr>
        <?php break;?>
        
        <?php case 'custom':?>
        <?php if( $key == 'lat'): ?>
        <?php $i--;?>
        <tr id="center-map"  style="visibility:collapse;">
        	<td><?=_e('Pan and zoom until find the position, and when ready save the position', 'lfh')?></td>
            <td colspan="2" id="text-pan">
            <div id="map-position" >&nbsp;</div>
            <input type="button" name="save-center" value="<?=ucfirst(__('save', 'lfh'))?>"  />
        </td></tr>
        <input type="hidden" name="<?=$id?>" value="<?=$default?>"/>
        <?php endif; ?>
        <?php break;?>
        
    <?php endswitch;?>
        
  
    <?php endforeach;?>
      </table>
        <div>
            <label for="reset-map"></label>
            <input type ="reset"  name="reset-map" value="<?=ucfirst(__('reset' , 'lfh'))?>" />
            
        </div>
        
    </form>
  </div>